# This workflow automatically updates the profile README. It runs the update_readme.py script once per day. That script builds a new README file which includes some recent posts from blog.taha.gg

name: Update profile README

on:
  schedule:
    - cron: "0 0 * * *" # Runs every day at midnight UTC

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write

jobs:
  # This workflow contains a single job called "build"
  update-readme:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests feedparser

      - name: Run update script
        run: python update_readme.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'Github Actions'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          # Only commit if there are changes
          git diff --quiet && git diff --staged --quiet || git commit -m 'Update README with latest posts'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
